### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by scramble45** [101100/lsm303-rx#3]
````
Error: Cannot find module 'lsm303-rx'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_code/new_accel_test_rx.js:2:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
````

node version: 6.4.0

**Comment by 101100** [comment]
Did you install the module?  To do that, you need to do something like:

```
npm install lsm303-rx
```

That will install the module in a folder called `node_modules`.

**Comment by scramble45** [comment]
Yes
````
npm i https://github.com/101100/lsm303-rx.git
````

then: 
````
 npm ls | grep lsm303-rx
````
````
├── lsm303-rx@1.1.0 extraneous (git+https://github.com/101100/lsm303-rx.git#6fddc7507e98b4a89ef6a10589899cacde4ce59f)
````

Shows installed but when using your example code it says it cant find it.

**Comment by 101100** [comment]
You can't directly use the github repository like that.  The [main](https://github.com/101100/lsm303-rx/blob/master/package.json#L15) file is a generated file (TypeScript compiler output) that is not committed.

**Comment by scramble45** [comment]
So if I bring it down...
````
git clone https://github.com/101100/lsm303-rx.git
````
then 
````npm i```` ?

The thing is I need to modify the content of the i2c address and some control registers for my spark fun lsm303 to work...

even if I just do a:
````
 npm install lsm303-rx
````

I'm still getting cannot find module... all my other modules are working and installing...

**Comment by scramble45** [comment]
Found part of the issue:
````
lsm303-rx@1.1.0~prepublish: cannot run in wd %s %s (wd=%s) lsm303-rx@1.1.0 tsc /node_code/lsm303-rx
````

looks like the type script compiler wasn't running not sure how it was passing...

then I did:
````
npm i lsm303-rx --unsafe-perm
````
and got:

````
TypeError: Lsm303Driver is not a constructor
    at Object.<anonymous> (/node_code/new_accel_test_rx.js:10:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

````

**Comment by 101100** [comment]
Ah, you want to change the code...  Can you elaborate on what you need to change?  I'd like to add flags so modification isn't needed to make it work.

In the mean time, if you do:

```
cd node_modules/lsm303-rx
npm install
```

Then the Typescript compiler will be installed and the compiled files created.  Then you could modify `src/constants.js` to see if you can get it working.

**Comment by scramble45** [comment]
See above

Also I will go through once I can get the module partially working and tell you what flags.

**Comment by 101100** [comment]
Where did you run `npm i lsm303-rx --unsafe-perm`?

What code caused `TypeError: Lsm303Driver is not a constructor`?

**Comment by scramble45** [comment]
I had to run with --unsafe-perm before the type script compiler would even acknowledge installing your module properly. TSC wouldnt run without that parameter added. As for the code that caused the not a constructor, that's example code:

````
var i2c = require("i2c-bus");
var Lsm303Driver = require("lsm303-rx");

var options = {
    // looking at the source code, the synchronous and
    // asynchronous open functions are identical
    i2c: i2c.openSync(1)
};

lsm303 = new Lsm303Driver(options);

console.log('Reading 10 headings...');
lsm303.streamHeadings(500) // sample every 500 ms
    .take(10)
    .subscribe(
        function (heading) {
            console.log('Next: ' + heading);
        },
        function (err) {
            console.log('Error: ' + err);
        },
        function () {
            console.log('Completed');
        }
    );
````

**Comment by 101100** [comment]
Ah, now I know the issue.  The example needs to be updated; I forgot about that when I changed the export style a while ago.  Try this:

```js
var Lsm303Driver = require("lsm303-rx").Lsm303Driver;
```

**Comment by 101100** [comment]
The `--unsafe-perm` requirement indicates that you are running as `root`.  As a typical user, it would work without that flag.

**Comment by scramble45** [comment]
Using : ````var Lsm303Driver = require("lsm303-rx").Lsm303Driver;````

fixed that, I'm thinking some of my other registers are messed up as I am seeing a bunch of NaN on the read.

I had to change the address of my accelerometer to 1D.
````
Reading 10 headings...
Next: NaN
Next: NaN
Next: NaN
Next: NaN
Next: NaN
Next: NaN
Next: NaN
Next: NaN
Next: NaN
Next: NaN
Completed
````

The module:
http://www.st.com/content/ccc/resource/technical/document/datasheet/59/aa/fb/3b/85/9e/4e/0a/DM00089896.pdf/files/DM00089896.pdf/jcr:content/translations/en.DM00089896.pdf


i2cdetect:

````
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- 1d 1e --
20: 20 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
````

**Comment by 101100** [comment]
I would try changing the mag address to `0x1e`.  Then try out the raw magnometer[example](https://github.com/101100/lsm303-rx/blob/master/examples/magnometer.ts).  If that works, then try getting the raw accelorometer example working using [this example](https://github.com/101100/lsm303-rx/blob/master/examples/accelerometer.ts) and different addresses. Once both of those work, the headings example should work (but may need calibration).

**Comment by scramble45** [comment]
yea the mag address was already 0x1E in constants, I am seeing some data with the raw accelormeter but no Mag data just NaN

**Comment by scramble45** [comment]
I went another route and used the lsm303 library and am completing the code where they left off. Thanks

**Comment by 101100** [comment]
@scramble45 I'm just curious: was the address change the only change needed, were there other fundamental changes, or did you just want something that didn't use RxJS?  Thanks.

**Comment by scramble45** [comment]
I changed the address but could never get the mag working, also I am not a fan of RxJS for what we are trying to do. Keeping it native, so it works well with things like 'Enclose JS' is mainly what we am after. Things like coffee script and RxJS cause problems for it. Thanks for the help though.
